spring:
  application:
    name: restaurant-management

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: false

jwt:
  access-token:
    expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600} # 1 hour in seconds
  refresh-token:
    expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800} # 7 days in seconds
  secret-key: ${JWT_SECRET_KEY:IIxZ4+TL7ed8Gu2KDJxqbTMARthJHDM5GhN3kKzYITs=}